# Generated by Django 4.1.3 on 2023-03-05 17:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoles', models.CharField(choices=[('aviationMilitaire', "Ecole spécialisé dans l'avation militaire"), ('aviationCivile', "Ecole spécialisé dans l'avation civile"), ('aviationLoisirSportif', "Ecole spécialisé dans l'avation loisir et sportive")], default='aviationCivile', max_length=50)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('8h', '8h'), ('10h', '10h'), ('12h', '12h'), ('14h', '14h'), ('16h', '16h'), ('18h', '18h'), ('20h', '20h')], default='10h', max_length=10)),
                ('time_ordered', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
